### ISSUE TITLE
[feature request] download file as a stream

### ISSUE THREAD

**Issue by alexgiuvara** [usmanhalalit/laracsv#11]
A great addition would be the option to download the file as a stream `response()->stream($callback, 200, $headers)`

**Comment by usmanhalalit** [comment]
Now you can pass different League CSV writers, like:
```
$csvExporter = new \Laracsv\Export(\League\Csv\Writer::createFromStream($stream));
```

Does it solve your issue?
More: http://csv.thephpleague.com/8.0/filtering/
