### ISSUE TITLE
Using camel-cased relation names will break the export

### ISSUE THREAD

**Issue by brainless81** [usmanhalalit/laracsv#16]
I'm having relations in my model such as:

    $csvExporter->build($test, [
        'id'                            => 'Forecast ID',
        'aptInitiative.initiative_name' => 'Initiative Name'
    ])->download();

Since in Laravel, the default handling is to convert such relation names to snake-case while converting to an array (see `Model::toArray()`), this will break your package because of the most recent changes.

Causing commit is: 3e94f0c65b240ce7dddbfa3e7cd797729520021b
and the commit 7706f47a406745eafe80933fd9d0bc592e6578bf won't be possible as it deals only with arrays.

Thats why I propose to go this way: https://github.com/usmanhalalit/laracsv/pull/17

**Comment by brainless81** [comment]
https://github.com/usmanhalalit/laracsv/pull/17

**Comment by usmanhalalit** [comment]
@lucasmichot can you please help me with this issue? It's not something I'm capable of.

**Comment by lucasmichot** [comment]
@usmanhalalit and @brainless81 let's go on with https://github.com/usmanhalalit/laracsv/pull/17

**Comment by lucasmichot** [comment]
It would be good to add an assertion on #17
