### ISSUE TITLE
Dev package composer requirements

### ISSUE THREAD

**Issue by eberkund** [usmanhalalit/laracsv#19]
Can something be done about this line in the composer.json file?

    "illuminate/database": "5.2.*@dev",

The dev part is causing issues for when I try to do a composer update. Is there something specific that is not in the stable branch that this package depends on?

**Comment by orkhanahmadov** [comment]
Same problem. Cannot update composer because of this.

**Comment by usmanhalalit** [comment]
It has been fixed, sorry for the trouble.

Thanks @eberkund and @orkhanahmadov . You can run `composer update` now, please let me if you face any trouble.

**Comment by orkhanahmadov** [comment]
Can confirm, it is working now.
Thanks.
