### ISSUE TITLE
utf-8 ( specially Arabic Language ) 

### ISSUE THREAD

**Issue by abusalameh** [usmanhalalit/laracsv#2]
package is working fine and so pretty! 

but it doesn't support Arabic it displays as rubbish data 

example : 

I tried username = 'رجا ابو سلامة'

the result in the csv file 'Ø±Ø¬Ø§ Ø£Ø¨Ùˆ Ø³Ù„Ø§Ù…Ø©'

**Comment by PascaleBeier** [comment]
Hey there,

> LaraCSV uses League CSV. You can do what League CSV is able to do. You can get the underlying League CSV instance by calling:

`$csv = $csvExporter->getCsv();`

Here you can manipulate the BOM as stated in the League/Csv [docs](http://csv.thephpleague.com/8.0/bom/).

**Comment by usmanhalalit** [comment]
@abusalameh it works fine for me out of the box, I've also created some tests for it:
https://github.com/usmanhalalit/laracsv/commit/c845b3b40f29768b2d9491a772504c674672c6bb#diff-58cc0cf8e31fd01475e8c817dc4b83d7R61

If you can share your code then it might help.


Thanks @PascaleBeier for the comment.
