### ISSUE TITLE
Documentation: What's about records count limitation 

### ISSUE THREAD

**Issue by saidbakr** [usmanhalalit/laracsv#21]
In the documentation there is no any hint or mention about exporting large models. For example, suppose User model with more than 40K users and we want to export, id, name, email, age, address and salary.
How could the package deals with memory limitation and processing time?

**Comment by usmanhalalit** [comment]
@saidbakr You can stream the output, you can pass a stream writer in the constructor.

https://github.com/usmanhalalit/laracsv/blob/master/src/Laracsv/Export.php#L33
http://csv.thephpleague.com/8.0/instantiation/#abstractcsvcreatefromstream

**Comment by delmicio** [comment]
@usmanhalalit can you please provide an example of stream with your lib?
```PHP
use League\Csv\Writer;

$writer = Writer::createFromStream(fopen('php://output', 'w'));
$csvExporter = new \Laracsv\Export($writer);
$users = User::get();

// Register the hook before building
$csvExporter->beforeEach(function ($user) {
    $user->created_at = date('f', strtotime($user->created_at)); 
});

$csvExporter->build($users, ['email', 'name' => 'Full Name', 'created_at' => 'Joined']);
```
Is this the correct approach?

**Comment by usmanhalalit** [comment]
@delmicio yes
