### ISSUE TITLE
Cannot modify header information - headers already sent by (output started at phar:///usr/local/Cellar/phpunit/7.5.1/bin/phpunit/phpunit/Util/Printer.php:109)

### ISSUE THREAD

**Issue by nexxai** [usmanhalalit/laracsv#26]
I use LaraCsv for my site and it works great but I realized I never wrote a test for the controllers that use it for. I wrote my test but am now running into the title issue using the following code (simplified for ease of reading):

```
$data = Data::all();

$csvExporter = new \Laracsv\Export();
$csvExporter->build($data, [
    'dataTitle' => 'Data'
]);

$csvExporter->download('downloadfile.csv');
```

What I'm trying to do is test that the file is auto-downloaded, but the only way I've found to do that is by doing this:

```
$response = $this->call('GET', route('export.download'));
$this->assertTrue($response->headers->get('content-type') == 'text/csv;charset=UTF-8');
$this->assertTrue($response->headers->get('content-disposition') == 'attachment; filename="downloadfile.csv"');
```

But (only in testing) I get this error: 

`ErrorException: Cannot modify header information - headers already sent by (output started at phar:///usr/local/Cellar/phpunit/7.5.1/bin/phpunit/phpunit/Util/Printer.php:109) in file /Users/nexxai/code/vendor/league/csv/src/AbstractCsv.php on line 361`

Is there another way I can test that the file is being properly downloaded, since it appears that PHPunit is pre-setting the headers before LaraCsv has the opportunity to do so?

**Comment by nexxai** [comment]
Turns out I needed to replace 

`/** @test */
`
With

```
/**
* @runInSeparateProcess
*/
```

**Comment by nexxai** [comment]
Ok, I lied.  After adding that to the docblock, it did *not* solve the problem.  I wasn't paying attention and was running the test above this one by accident, which just happened to have the exact same number of assertions.  Adding @runInSeparateProcess did not solve my issue, nor did adding "session_start();" to PHPUnit\Util\Printer.php immediately before line 114 (as suggested by someone else here: https://stackoverflow.com/questions/9745080/test-php-headers-with-phpunit?rq=1)

**Comment by stebogit** [comment]
same here!

**Comment by nexxai** [comment]
Yeah I gave up waiting for a fix and ended up switching to [Laravel Excel](https://laravel-excel.maatwebsite.nl/).  Super testable, great documentation.

**Comment by usmanhalalit** [comment]
@nexxai I don't see it as a library bug, this is the intended PHP behavior. If you want to test this route you've to mock `\Laracsv\Export`. Please correct me if I'm wrong.

**Comment by robsontenorio** [comment]
Running same issue. Is there any approach to test controllers ?

Controller
```php
 $csv = new Export();
        $csv->build($users, [
            'id'
            'name' 
            'email' 
        ])->download();
```

Test
```php
$this->get("users/download");
$response->assertHeader('content-type', 'text/csv');
```

Error on test
```php
Cannot modify header information - headers already sent by (output started at /var/www/api/vendor/phpunit/phpunit/src/Util/Printer.php:109)
```
