### ISSUE TITLE
How to get values from different models and result must be collection.

### ISSUE THREAD

**Issue by asimmehmood247** [usmanhalalit/laracsv#28]
I want to get Employees and their Bank account details. I can get employee details from employee model but can't from Bank modal. How to join them and result must be in a collection object. $csvpayroll=Employee::all(); 
$csvExporter = new \Laracsv\Export(); 
$csvExporter->build($csvpayroll, ['id','name','account'])->download();
 Thank you

**Comment by usmanhalalit** [comment]
Please check docs:
https://github.com/usmanhalalit/laracsv#model-relationships
