### ISSUE TITLE
Composer install uses League/CSV 9.x, which breaks advertised functionality

### ISSUE THREAD

**Issue by MrBMT** [usmanhalalit/laracsv#29]
Hi,

Installing this package via `composer require "usmanhalalit/laracsv:1.*@dev"` or `composer require "usmanhalalit/laracsv:dev-master"` results in League/CSV 9.x being installed provided you're using a new enough version of PHP/Laravel.

This however breaks some of the advertised functionality such as:
```
$csv = $csvExporter->getCsv();
$csv->toHTML(); // To output the CSV as an HTML table 
$csv->jsonSerialize(); // To turn the CSV in to an array 
```

This is due to this functionality being re-worked in 9.x.

It would either be worth limiting the version installed by composer (e.g. updating the composer.json
 require from `"league/csv": ">=8.2"` to `"league/csv": "8.*"`) or updating the documentation to reflect the functionality mentioned is only available in League CSV 8.x.

For now this can be worked arround by first installing laracsv as normal, then afterwards running `composer require "league/csv:8.x"` which will downgrade the version of League/CSV being used.

**Comment by usmanhalalit** [comment]
Fixed on 2.0, please install or update https://github.com/usmanhalalit/laracsv#installation
