### ISSUE TITLE
delimiter

### ISSUE THREAD

**Issue by jplajpla23** [usmanhalalit/laracsv#30]
I can choose the delimiter, the default is the comma (,) but I wanted the semicolon (;)

**Comment by usmanhalalit** [comment]
@jplajpla23 You can set a delimiter, please check https://github.com/usmanhalalit/laracsv/blob/master/tests/Laracsv/ExportTest.php#L223 .
This is a LaraCSV 2.0 example, so please make sure to update or use `getCsv()` instead of `getWriter()`.

**Comment by valigton** [comment]
> @usmanhalalit can you explain please? thank you

Just set de delimiter before build.

( I know it's old issue but, if someone needs... )

```
$csv = new \Laracsv\Export();

$csv->getWriter()->setDelimiter(";");
        
$csv->build($collection, [
    'field1',
    'field2'
]);
```
