### ISSUE TITLE
Wrong header set for download on Safari

### ISSUE THREAD

**Issue by stebogit** [usmanhalalit/laracsv#32]
Hi,
when using the `Writer::download` function, inside a Laravel controller, on Safari the file gets an additional `.html` extension, so it is downloaded as `myfile.csv.html`:
```php
public function myDownload(Request $request)
{
    // ...
    $csv = Writer::createFromFileObject(new \SplTempFileObject());
    // some $csv->insertOne($line) to create the csv ... 
    $csv->output('myfile.csv');
    return null;
}
```

I fixed the issue setting my own headers:
```php
return response($csv->getContent(), 200, [
    'Content-Encoding'          => 'none',
    'Content-Transfer-Encoding' => 'binary',
    'Content-Description'       => 'File Transfer',
    'Content-Type'              => 'text/csv; charset=UTF-8',
    'Content-Disposition'       => 'attachment; filename="myfile.csv"',
]);
```

I just wanted to post this here in case somebody else faces this problem.

**Comment by dirtbikr** [comment]
Thanks for posting this. My CSV files were not downloading on Chrome for Android. Appending the encoding/description/type to the response fixed the problem for me.

**Comment by usmanhalalit** [comment]
Piggy backing on League CSV to fix this
