### ISSUE TITLE
In Php 7.0 it is not working

### ISSUE THREAD

**Issue by vijayyuvasoft** [usmanhalalit/laracsv#33]
In Php 7.0 this package throwing error ..it is not working .. 
I am facing this error :  "Type error: Return value of Laracsv\Export::addHeader() must be an instance of Laracsv\void, none returned"

**Comment by usmanhalalit** [comment]
@vijayyuvasoft please show me your code.

**Comment by vijayyuvasoft** [comment]
Hello,

In PHP 7.2 this code is working fine:
---
          $userObj = User::find($id);
          $user_logs1 =  DB::table('viewed_followed_offers as vfo')
                            ->join('streamer_offers as so', 'so.id', '=',
'vfo.streamer_offer_id')
                            ->join('users as u', 'u.id', '=',
'vfo.viewer_id')
                            ->join('users as us', 'us.id', '=',
'so.user_id')
                            ->where('so.user_id',$id)
                            ->orWhere('vfo.viewer_id',$id)
                            ->orderBy('vfo.created_at', 'desc')
                            ->get(['vfo.*','so.user_id','so.status','u.name
as viewer_name','us.name as streamer_name']);

          $csvExporter = new \Laracsv\Export();
          $csvExporter->build($user_logs1, ['type','viewer_name',
'streamer_name','credit_earn','minute_viewed','request_ip',
'is_credits_revert' ,
'created_at'])->download($userObj->display_name.'.csv');
-----

Regards

**Comment by usmanhalalit** [comment]
@vijayyuvasoft which version of LaraCSV are you using, `2.0` or `1.0`?

**Comment by vijayyuvasoft** [comment]
2.0

**Comment by usmanhalalit** [comment]
LaraCSV `2.0` requires PHP 7.1, for older PHP versions please use `1.0`.

**Comment by vijayyuvasoft** [comment]
1.0 will work for 7.0 ?

**Comment by usmanhalalit** [comment]
Yes

**Comment by vijayyuvasoft** [comment]
Okay  I will test and let you know.. Thank You for prompt response.

**Comment by vijayyuvasoft** [comment]
On php 7.0 I have installed this version :
https://github.com/usmanhalalit/laracsv/tree/1.x

But I am getting this error :
----
Type error: Argument 1 passed to Laracsv\Export::addCsvRows() must be an
instance of Illuminate\Database\Eloquent\Collection, instance of
Illuminate\Support\Collection given, called in
/var/www/vendor/usmanhalalit/laracsv/src/Laracsv/Export.php on line 61
----

And I am using same code which was working in PHP 7.0 and Laracsv 2.0

**Comment by usmanhalalit** [comment]
@vijayyuvasoft `DB::table` doesn't return Eloquent Collection, rather it returns Support\Collection. However support for `Support\Collection` has been added to `2.0`.

**Comment by vijayyuvasoft** [comment]
Finally I upgrade the php version to 7.2 and it work .
Your provide package is nice but you need to information about the version
and dependencies in readme file.. that will help to developers.

Regards,
Vijay
