### ISSUE TITLE
save in specific directory instead of export and download

### ISSUE THREAD

**Issue by conmen80** [usmanhalalit/laracsv#35]
Hi, I use this package working good in laravel, instead of download the pdf, is that anyway I can save the pdf automatically in a certain directory? I need this function to be able to send as an attachment in a cron job. Please advise and thanks!!

**Comment by maczoe** [comment]
Hi, I managed to perform the expected behavior through getWriter ():

`$model = Model::get();`
`$csvExport = new Export();`
`$content = $csvExport->($model,['field1','field2'])->getWriter()->getContent();`
`Storage::disk('public')->put('file.csv', $content);`

**Comment by usmanhalalit** [comment]
Thanks @maczoe, that's correct.
