### ISSUE TITLE
LazyCollections

### ISSUE THREAD

**Issue by dacastro4** [usmanhalalit/laracsv#36]
> Argument 1 passed to Laracsv\Export::addCsvRows() must be an instance of Illuminate\Support\Collection, instance of Illuminate\Support\LazyCollection given, called in /Users/danielcastro/Projects/reporting-dashboard/vendor/usmanhalalit/laracsv/src/Laracsv/Export.php on line 80

Are you planning in supporting LazyCollection to build the CSV?

**Comment by dacastro4** [comment]
I created #37, I hope it works for you.

**Comment by usmanhalalit** [comment]
Fixed by #42
