### ISSUE TITLE
Download break loop

### ISSUE THREAD

**Issue by guimadalozzo** [usmanhalalit/laracsv#40]
When I execute the download, the loop foreach was break.

How download multiples CSVs?

`foreach ($teste->roboTesteEmpresa as $empresa) {
	$historicos = HistoricoCotacoes::all();
	$csvExporter = new \Laracsv\Export();
	$csvExporter->build($historicos, ['close'], ['header' => false])->output("test.csv");
}`

**Comment by usmanhalalit** [comment]
File download writes output, you can't force download of multiple files in one action.
