### ISSUE TITLE
Requiring issue

### ISSUE THREAD

**Issue by arkadiy93** [usmanhalalit/laracsv#41]
I tried installing the package by using `composer require usmanhalalit/laracsv:^2.0`

I got the following response: 
 `[InvalidArgumentException]
  Could not find package usmanhalalit/laracsv in a version matching 2.0`

**Comment by usmanhalalit** [comment]
Hey, working fine on my end on several attempts, also no one else has complained, maybe something wrong in your end?

<img width="740" alt="Screenshot 2020-01-25 at 11 26 58" src="https://user-images.githubusercontent.com/981039/73120426-acb4d380-3f65-11ea-91df-8b31a6ea48b7.png">
