### ISSUE TITLE
Support for chunked model input

### ISSUE THREAD

**Issue by LarsGrevelink** [usmanhalalit/laracsv#43]
Hi @usmanhalalit!

We're running into some memory issues when we're working with larger datasets. We could tackle this issue by using the `chunk` method on Eloquent's `Builder` classes. Would you be interested in adding an additional method to your package which allows the input of a `Builder` and "chunks" its way through all the results?

Love to make a PR for this.

Cheers!

**Comment by usmanhalalit** [comment]
Hey @LarsGrevelink! Yes, please 🙂

**Comment by LarsGrevelink** [comment]
I'll make an in-between pull request to make sure the style is the same across the file. For clarity, it gets its separate PR and I will explain some changes I made there as well. Will make it momentarily.

**Comment by LarsGrevelink** [comment]
@usmanhalalit did you find the time to take a look at the open pull requests? Would love to get your take on both of them. Thanks!

**Comment by usmanhalalit** [comment]
Sorry, my Saturday ran away from me, I'll have a look.

**Comment by LarsGrevelink** [comment]
Hi @usmanhalalit! Don't want to rush you but do you have an estimation when feedback is to be expected? I would rather update the package than update the implementation side in a project. It's okay to tackle it that way and leave the PR open for a while longer, just want to know what expectations to set on my side. Thanks in advance. 👍🏼

**Comment by usmanhalalit** [comment]
@LarsGrevelink reviewed the PR 🙂
