### ISSUE TITLE
After Download csv contains some garbage data

### ISSUE THREAD

**Issue by shoaib0906** [usmanhalalit/laracsv#48]
My function is like::
for($i=$serialfrom;$i<=($serialfrom+$download_qty-1);$i++){
                    $data['serial'][] = $serial['no'] = makeQR($i,$ticket_type);                                
                    $ticket = new Ticket;
                    $ticket->ticket_id = $serial['no'];
                    $ticket->ticket_class = $ticket->title;
                    $ticket->per_ticket_price = $data['price'];
                    $ticket->valid_till_date = $data['expirv'];
                    $ticket->venue_id = $data['ticket_venue'];
                    $c->add($ticket); 
            }           
            $csvExporter = new \Laracsv\Export();        
            $csvExporter->build($c, ['venue_id'=>'Venue Title', 'ticket_class' => 'Ticket Type', 
                'per_ticket_price' => 'Price','valid_till_date'=>'Expire Date','ticket_id'=>'Serial No'])->download('tickets.csv');

But after download its contains a lot of garbage like 

<script> Sfdump = window.Sfdump || (function (doc) { var refStyle = doc.createElement('style')
  "<span class=sf-dump-key>_token</span>" => "<span class=sf-dump-str title="40 characters">os9JgM4BrcEvI1pIrx4Px87Njeophgr8aIdaADw8</span>"

![csvbug](https://user-images.githubusercontent.com/14304400/86378298-5d727d80-bc3e-11ea-86c1-f43ea06e5d84.PNG)

**Comment by usmanhalalit** [comment]
@shoaib0906, looks like Laravel Debugbar or another debugger is interfering with the output, can you try disabling it?

**Comment by shoaib0906** [comment]
Sorry!!

I set APP_DEBUG=false for laravel which stop debugger for application.
And run php artisan config:cache for remove previsous state of configuration.
but same result.

For laravel how to stop debugger FYI::
https://stackoverflow.com/questions/48220709/how-to-safely-remove-laravel-debugbar/52528002#:~:text=You%20can%20enable%20or%20disable%20the%20debugbar%20during%20run%20time.&text=You%20can%20execute%20composer%20remove,disable()%3B%20in%20your%20AppServiceProvider%20.

**Comment by usmanhalalit** [comment]
Can you try printing the output of csv like `dd($csvExporter->getWriter()->getContent())` rather than downloading?
https://github.com/usmanhalalit/laracsv#advanced-outputs

If it looks okay then certainly a debugger or something similar is causing the issue.

**Comment by shoaib0906** [comment]
Now Only value is there no garbagge.

**Comment by usmanhalalit** [comment]
Then some package is interfering with your response, the package has nothing to do here really, it simply uses another package's (LeagueCSV) download function.
