### ISSUE TITLE
Pass to Front End using React

### ISSUE THREAD

**Issue by ticholNyler** [usmanhalalit/laracsv#49]
I need to pass this to the front end as a stream possibly because I am using Controllers as the api to a React front end.

**Comment by usmanhalalit** [comment]
You can output the csv data expose via API and let frontend deal with it:
https://github.com/usmanhalalit/laracsv#advanced-outputs

You can pass a stream writer if you need streaming
https://github.com/usmanhalalit/laracsv/blob/master/src/Laracsv/Export.php#L54
