### ISSUE TITLE
Add new row after specific key/condition

### ISSUE THREAD

**Issue by koo27** [usmanhalalit/laracsv#50]
This is a question/request. I don't know if it's already possible to do, but I couldn't figure out how to anyway.
My aim is to add new rows every X rows from the collection or (better) after a specific condition.

For example I have a collection of Users and I'd like to insert a row with a symbol, like "#" in every column. But this doesn't have to change a row from the User Collection, just add a new one.

```
$csvExporter->beforeEach(function ($user) {
       if ( // some condition ) {
	   $user->id = '#';
           $user->name = '#';
           // etc.
       }
});
```
This would work, but it changes the specific row. It should add a new one, like the header within the build method.

**Comment by koo27** [comment]
I solved my issue by creating a new collection using a foreach loop on the original one; that means avoiding using the beforeEach method of this package.
However it could be useful to have a method to add new rows.

**Comment by usmanhalalit** [comment]
Good to know @koo27
