### ISSUE TITLE
Update The version of Installation topic at readme

### ISSUE THREAD

**Issue by samuel-lujan** [usmanhalalit/laracsv#51]
At installation installation topic at readme says `composer require usmanhalalit/laracsv:^2.0` there is a new release and composer are tellig usmanhalalit/laracsv:^2.0 was not found, then we need update to `composer require usmanhalalit/laracsv:^2.1`

**Comment by samuel-lujan** [comment]
I has changed it in the repository if you allow me I can create some pull request

**Comment by usmanhalalit** [comment]
Thank you, please feel free to create a PR.

**Comment by samuel-lujan** [comment]
there it is: 
https://github.com/usmanhalalit/laracsv/pull/52

So much thanks! this helped me a lot
