### ISSUE TITLE
csv package is not working in Laravel 8

### ISSUE THREAD

**Issue by nasirjamil786** [usmanhalalit/laracsv#55]
Dear Usman,
Thank you for your very useful package however I am working in Laravel 8 , but it is not woring.
I even updated the composer, re installed your package 2.0 . But some how it is not building and not downloading the file.
I run a very simple query, can you please help me fix that

**Comment by saularis** [comment]
Hi @nasirjamil786, What error do you see? Please provide more details. Thanks!

**Comment by nasirjamil786** [comment]
Dear Saularis, it does not do anything ,
$users = User::get(); // All users
$csvExporter = new \Laracsv\Export();
$csvExporter->build($users, ['email', 'name'])->download();
it does not do anything 
i checked with dd($csvExporter) and class was there but i do not know why it is not working 
I then composer update but still not working

**Comment by saularis** [comment]
Just tested on my local, it's working. There's nothing wrong with Laracsv. 

Here are some suggestions:
1. Check if you have data on your user table.
2. Check if the route is set up correctly.

**Comment by nasirjamil786** [comment]
Thank you, the data is there , rout is also correct, I think may be problem with installation , any suggestion for debugging / please . I have removed the package and then added again but still not functioning.
