### ISSUE TITLE
New Line Character

### ISSUE THREAD

**Issue by lovishchawla** [usmanhalalit/laracsv#56]
Hi Usman,

I have a paragragh in one of my columns in one table, which contains new line characters. The csv file on exporting/downloading partitions the paragraph into different cells each starting from new row (1st column). Do you have any solution for this?

**Comment by saularis** [comment]
@lovishchawla Did you try using Laravel Model accessor?

https://laravel.com/docs/8.x/eloquent-mutators#defining-an-accessor
